### 5. **Atualizar docker-compose.yml com variáveis reais**
```yaml
version: '3.8'

services:
  backend:
    build: ./PreSystem.StockControl
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JWT_SECRET=${JWT_SECRET:-sua-chave-secreta-muito-segura-123456}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - PORT=5000
  
  frontend:
    build: ./stock-control-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:5000/api}
    depends_on:
      - backend