[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd PreSystem.StockControl",
  "dotnet restore",
  "dotnet publish -c Release -o ./publish"
]

[start]
cmd = "cd PreSystem.StockControl && dotnet ./publish/PreSystem.StockControl.WebApi.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"