
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd PreSystem.StockControl && dotnet PreSystem.StockControl.WebApi/bin/Release/net8.0/publish/PreSystem.StockControl.WebApi.dll"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10